/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://wwhip4irajekbpsexsoq3yumhi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_e91AZzxL3",
        "userPoolWebClientId": "4unb7pc4bjnanr1hamf3hdn3h",
        "identityPoolId": "us-east-1:3ce17ded-0e07-4e61-b71b-168259d9fd42"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-1fz7jfidi5fo8",
            "region": "us-east-1"
        }
    }
};


export default awsmobile;
